/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignsIndexRouteImport } from './routes/designs.index'
import { Route as ConsultantsIndexRouteImport } from './routes/consultants.index'
import { Route as DesignsResultRouteImport } from './routes/designs.result'
import { Route as DesignsIdRouteImport } from './routes/designs.$id'
import { Route as ConsultantsIdRouteImport } from './routes/consultants.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIndexRoute = DesignsIndexRouteImport.update({
  id: '/designs/',
  path: '/designs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantsIndexRoute = ConsultantsIndexRouteImport.update({
  id: '/consultants/',
  path: '/consultants/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsResultRoute = DesignsResultRouteImport.update({
  id: '/designs/result',
  path: '/designs/result',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsIdRoute = DesignsIdRouteImport.update({
  id: '/designs/$id',
  path: '/designs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantsIdRoute = ConsultantsIdRouteImport.update({
  id: '/consultants/$id',
  path: '/consultants/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/generate': typeof GenerateRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/designs/$id': typeof DesignsIdRoute
  '/designs/result': typeof DesignsResultRoute
  '/consultants/': typeof ConsultantsIndexRoute
  '/designs/': typeof DesignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/generate': typeof GenerateRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/designs/$id': typeof DesignsIdRoute
  '/designs/result': typeof DesignsResultRoute
  '/consultants': typeof ConsultantsIndexRoute
  '/designs': typeof DesignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/generate': typeof GenerateRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wallet': typeof WalletRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/designs/$id': typeof DesignsIdRoute
  '/designs/result': typeof DesignsResultRoute
  '/consultants/': typeof ConsultantsIndexRoute
  '/designs/': typeof DesignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/forgot-password'
    | '/generate'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/profile'
    | '/referral'
    | '/register'
    | '/sessions'
    | '/settings'
    | '/sitemap.xml'
    | '/wallet'
    | '/consultants/$id'
    | '/designs/$id'
    | '/designs/result'
    | '/consultants/'
    | '/designs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/forgot-password'
    | '/generate'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/profile'
    | '/referral'
    | '/register'
    | '/sessions'
    | '/settings'
    | '/sitemap.xml'
    | '/wallet'
    | '/consultants/$id'
    | '/designs/$id'
    | '/designs/result'
    | '/consultants'
    | '/designs'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/forgot-password'
    | '/generate'
    | '/home'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/otp'
    | '/profile'
    | '/referral'
    | '/register'
    | '/sessions'
    | '/settings'
    | '/sitemap.xml'
    | '/wallet'
    | '/consultants/$id'
    | '/designs/$id'
    | '/designs/result'
    | '/consultants/'
    | '/designs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GenerateRoute: typeof GenerateRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WalletRoute: typeof WalletRoute
  ConsultantsIdRoute: typeof ConsultantsIdRoute
  DesignsIdRoute: typeof DesignsIdRoute
  DesignsResultRoute: typeof DesignsResultRoute
  ConsultantsIndexRoute: typeof ConsultantsIndexRoute
  DesignsIndexRoute: typeof DesignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/': {
      id: '/designs/'
      path: '/designs'
      fullPath: '/designs/'
      preLoaderRoute: typeof DesignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultants/': {
      id: '/consultants/'
      path: '/consultants'
      fullPath: '/consultants/'
      preLoaderRoute: typeof ConsultantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/result': {
      id: '/designs/result'
      path: '/designs/result'
      fullPath: '/designs/result'
      preLoaderRoute: typeof DesignsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs/$id': {
      id: '/designs/$id'
      path: '/designs/$id'
      fullPath: '/designs/$id'
      preLoaderRoute: typeof DesignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultants/$id': {
      id: '/consultants/$id'
      path: '/consultants/$id'
      fullPath: '/consultants/$id'
      preLoaderRoute: typeof ConsultantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GenerateRoute: GenerateRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WalletRoute: WalletRoute,
  ConsultantsIdRoute: ConsultantsIdRoute,
  DesignsIdRoute: DesignsIdRoute,
  DesignsResultRoute: DesignsResultRoute,
  ConsultantsIndexRoute: ConsultantsIndexRoute,
  DesignsIndexRoute: DesignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
